language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install gffutils
  - python setup.py build

script:
  - pytest tests/test_readers.py
  - ./nosqlbiosets/uniprot/index.py --help
  - ./nosqlbiosets/uniprot/query.py --help
  - ./nosqlbiosets/intenz/index.py --help
  - ./nosqlbiosets/intenz/query.py --help
  - ./nosqlbiosets/metanetx/index.py --help
  - ./hmdb/index.py --help
  - ./hmdb/drugbank.py --help
